[package]
name = "HotFix"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
tokio = { version = "1.52.1", features = ["full"] }
askama = "0.15.6"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio"] }
aes-gcm = "0.10.3"
tower = "0.5.3"
reqwest = "0.13.3"
tower-http = { version = "0.6", features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
argon2 = "0.5.3"
hex = "0.4.3"
hmac = "0.13.0"
sha2 = "0.10.9"
tracing = "0.1.44"
