TRUNCATE problems CASCADE;

INSERT INTO problems (id, name, topics, language, difficulty, correct_version, incorrect_version, tests, time_limit_seconds, description, solved_count, created_at) VALUES
                                                                                                                                                                        (
                                                                                                                                                                            gen_random_uuid(),
                                                                                                                                                                            'Sum of Array',
                                                                                                                                                                            ARRAY['arrays', 'loops'],
                                                                                                                                                                            'rust',
                                                                                                                                                                            'easy',
                                                                                                                                                                            'use std::io;\nuse std::io::BufRead;\n\nfn main() {\n    let stdin = io::stdin();\n    let mut lines = stdin.lock().lines();\n    let n: usize = lines.next().unwrap().unwrap().trim().parse().unwrap();\n    let nums_line = lines.next().unwrap().unwrap();\n    let numbers: Vec<i32> = nums_line.split_whitespace().map(|x| x.parse().unwrap()).collect();\n    let sum: i32 = numbers.iter().sum();\n    println!("{}", sum);\n}',
                                                                                                                                                                            'use std::io;\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let n: i32 = input.trim().parse().unwrap();\n    let mut sum = 0;\n    for _ in 0..n {\n        let mut num = String::new();\n        io::stdin().read_line(&mut num).unwrap();\n        sum += num.trim().parse::<i32>().unwrap();\n    }\n    println!("{}", sum);\n}',
                                                                                                                                                                            '[{"input": "3\n1 2 3", "expected_output": "6"}, {"input": "4\n10 20 30 40", "expected_output": "100"}, {"input": "5\n5 5 5 5 5", "expected_output": "25"}]'::jsonb,
                                                                                                                                                                            30,
                                                                                                                                                                            'Calculate the sum of all numbers in the array. Input: first line N, second line N space-separated integers. Output: their sum.',
                                                                                                                                                                            0,
                                                                                                                                                                            NOW()
                                                                                                                                                                        ),
                                                                                                                                                                        (
                                                                                                                                                                            gen_random_uuid(),
                                                                                                                                                                            'Find Maximum',
                                                                                                                                                                            ARRAY['arrays', 'max'],
                                                                                                                                                                            'rust',
                                                                                                                                                                            'easy',
                                                                                                                                                                            'use std::io;\nuse std::io::BufRead;\n\nfn main() {\n    let stdin = io::stdin();\n    let mut lines = stdin.lock().lines();\n    let n: usize = lines.next().unwrap().unwrap().trim().parse().unwrap();\n    let nums_line = lines.next().unwrap().unwrap();\n    let numbers: Vec<i32> = nums_line.split_whitespace().map(|x| x.parse().unwrap()).collect();\n    let max = *numbers.iter().max().unwrap();\n    println!("{}", max);\n}',
                                                                                                                                                                            'use std::io;\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let n: i32 = input.trim().parse().unwrap();\n    let mut max = 0;\n    for _ in 0..n {\n        let mut num = String::new();\n        io::stdin().read_line(&mut num).unwrap();\n        let val = num.trim().parse::<i32>().unwrap();\n        if val > max {\n            max = val;\n        }\n    }\n    println!("{}", max);\n}',
                                                                                                                                                                            '[{"input": "3\n1 5 3", "expected_output": "5"}, {"input": "4\n10 20 5 15", "expected_output": "20"}, {"input": "3\n-1 -5 -3", "expected_output": "-1"}]'::jsonb,
                                                                                                                                                                            30,
                                                                                                                                                                            'Find the maximum number in the array. Input: first line N, second line N space-separated integers. Output: the maximum value.',
                                                                                                                                                                            0,
                                                                                                                                                                            NOW()
                                                                                                                                                                        ),
                                                                                                                                                                        (
                                                                                                                                                                            gen_random_uuid(),
                                                                                                                                                                            'Even Numbers Count',
                                                                                                                                                                            ARRAY['arrays', 'conditionals'],
                                                                                                                                                                            'rust',
                                                                                                                                                                            'medium',
                                                                                                                                                                            'use std::io;\nuse std::io::BufRead;\n\nfn main() {\n    let stdin = io::stdin();\n    let mut lines = stdin.lock().lines();\n    let n: usize = lines.next().unwrap().unwrap().trim().parse().unwrap();\n    let nums_line = lines.next().unwrap().unwrap();\n    let numbers: Vec<i32> = nums_line.split_whitespace().map(|x| x.parse().unwrap()).collect();\n    let count = numbers.iter().filter(|&&x| x % 2 == 0).count();\n    println!("{}", count);\n}',
                                                                                                                                                                            'use std::io;\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let n: i32 = input.trim().parse().unwrap();\n    let mut count = 0;\n    for _ in 0..n {\n        let mut num = String::new();\n        io::stdin().read_line(&mut num).unwrap();\n        let val: i32 = num.trim().parse().unwrap();\n        if val / 2 == 0 {\n            count += 1;\n        }\n    }\n    println!("{}", count);\n}',
                                                                                                                                                                            '[{"input": "4\n1 2 3 4", "expected_output": "2"}, {"input": "5\n2 4 6 8 10", "expected_output": "5"}, {"input": "3\n1 3 5", "expected_output": "0"}]'::jsonb,
                                                                                                                                                                            30,
                                                                                                                                                                            'Count how many even numbers are in the array. Input: first line N, second line N space-separated integers. Output: the count of even numbers.',
                                                                                                                                                                            0,
                                                                                                                                                                            NOW()
                                                                                                                                                                        ),
                                                                                                                                                                        (
                                                                                                                                                                            gen_random_uuid(),
                                                                                                                                                                            'Reverse Array',
                                                                                                                                                                            ARRAY['arrays', 'reverse'],
                                                                                                                                                                            'rust',
                                                                                                                                                                            'medium',
                                                                                                                                                                            'use std::io;\nuse std::io::BufRead;\n\nfn main() {\n    let stdin = io::stdin();\n    let mut lines = stdin.lock().lines();\n    let n: usize = lines.next().unwrap().unwrap().trim().parse().unwrap();\n    let nums_line = lines.next().unwrap().unwrap();\n    let numbers: Vec<String> = nums_line.split_whitespace().map(|x| x.to_string()).collect();\n    let reversed: Vec<String> = numbers.into_iter().rev().collect();\n    println!("{}", reversed.join(" "));\n}',
                                                                                                                                                                            'use std::io;\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let n: i32 = input.trim().parse().unwrap();\n    let mut arr = Vec::new();\n    for _ in 0..n {\n        let mut num = String::new();\n        io::stdin().read_line(&mut num).unwrap();\n        arr.push(num.trim().to_string());\n    }\n    for i in 0..n {\n        print!("{} ", arr[i as usize]);\n    }\n}',
                                                                                                                                                                            '[{"input": "3\n1 2 3", "expected_output": "3 2 1"}, {"input": "4\n10 20 30 40", "expected_output": "40 30 20 10"}, {"input": "5\n1 2 3 4 5", "expected_output": "5 4 3 2 1"}]'::jsonb,
                                                                                                                                                                            30,
                                                                                                                                                                            'Reverse the order of elements in the array. Input: first line N, second line N space-separated integers. Output: the reversed sequence.',
                                                                                                                                                                            0,
                                                                                                                                                                            NOW()
                                                                                                                                                                        ),
                                                                                                                                                                        (
                                                                                                                                                                            gen_random_uuid(),
                                                                                                                                                                            'Fibonacci Number',
                                                                                                                                                                            ARRAY['math', 'fibonacci'],
                                                                                                                                                                            'rust',
                                                                                                                                                                            'hard',
                                                                                                                                                                            'use std::io;\n\nfn fib(n: u32) -> u32 {\n    match n {\n        0 => 0,\n        1 => 1,\n        _ => fib(n - 1) + fib(n - 2),\n    }\n}\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let n: u32 = input.trim().parse().unwrap();\n    println!("{}", fib(n));\n}',
                                                                                                                                                                            'use std::io;\n\nfn fib(n: u32) -> u32 {\n    match n {\n        0 => 0,\n        1 => 1,\n        _ => fib(n - 1),\n    }\n}\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let n: u32 = input.trim().parse().unwrap();\n    println!("{}", fib(n));\n}',
                                                                                                                                                                            '[{"input": "5", "expected_output": "5"}, {"input": "10", "expected_output": "55"}, {"input": "7", "expected_output": "13"}]'::jsonb,
                                                                                                                                                                            30,
                                                                                                                                                                            'Calculate the N-th Fibonacci number (F0 = 0, F1 = 1). Input: single integer N. Output: the N-th Fibonacci number.',
                                                                                                                                                                            0,
                                                                                                                                                                            NOW()
                                                                                                                                                                        ),
                                                                                                                                                                        (
                                                                                                                                                                            gen_random_uuid(),
                                                                                                                                                                            'Prime Check',
                                                                                                                                                                            ARRAY['math', 'prime'],
                                                                                                                                                                            'rust',
                                                                                                                                                                            'hard',
                                                                                                                                                                            'use std::io;\n\nfn is_prime(n: u32) -> bool {\n    if n < 2 { return false; }\n    for i in 2..=(n as f64).sqrt() as u32 {\n        if n % i == 0 { return false; }\n    }\n    true\n}\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let n: u32 = input.trim().parse().unwrap();\n    println!("{}", if is_prime(n) { "prime" } else { "not prime" });\n}',
                                                                                                                                                                            'use std::io;\n\nfn is_prime(n: u32) -> bool {\n    if n < 2 { return false; }\n    for i in 2..n {\n        if n % i == 0 { return false; }\n    }\n    true\n}\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let n: u32 = input.trim().parse().unwrap();\n    println!("{}", if is_prime(n) { "prime" } else { "not prime" });\n}',
                                                                                                                                                                            '[{"input": "7", "expected_output": "prime"}, {"input": "10", "expected_output": "not prime"}, {"input": "17", "expected_output": "prime"}]'::jsonb,
                                                                                                                                                                            30,
                                                                                                                                                                            'Check if a number is prime. Input: single integer N. Output: "prime" if N is prime, "not prime" otherwise.',
                                                                                                                                                                            0,
                                                                                                                                                                            NOW()
                                                                                                                                                                        );

SELECT name, difficulty, time_limit_seconds FROM problems;